fix: generate type declarations for build
Trendyol/baklava pull request #278
Opened 2022-10-12 14:45 UTC by olkeoguz

Includes 
* Generating the types with tsc,
* Fixing the generate-react-exports.js by including all the ts component file imports and hooking up the correct component to the "createComponent" function provided by @lit-labs/react
* Updating the docs for the beta version.

Closes #272.

2022-10-12 15:04 UTC, muratcorlu requested changes

2022-10-12 15:06 UTC, muratcorlu commented on scripts/generate-react-exports.js
> +  importStatements.push(`import ${Component} from "./${importPath}";`);
If you just need types, maybe you can try [import type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html).

2022-10-12 23:28 UTC, olkeoguz commented on scripts/generate-react-exports.js
> +  importStatements.push(`import ${Component} from "./${importPath}";`);
In order to generate the React element, we need to provide our component as the third argument of the createComponent function. 

Currently we are setting this argument as `customElements.get('${fileName}')` and this stays as a string in the generated baklava-react.ts file.

See the description below.

https://github.com/lit/lit/tree/main/packages/labs/react

![image](https://user-images.githubusercontent.com/70342517/195464684-ea1b91d9-704d-4061-b2ca-7fe689513da7.png)

I used npm pack to try our package locally in a CRA and get the error you mentioned.

Maybe we can access our component in different way. Any suggestion?

2022-10-13 06:56 UTC, muratcorlu commented on scripts/generate-react-exports.js
> +  importStatements.push(`import ${Component} from "./${importPath}";`);
Maybe we can just set a type for it:

```ts
import type ${Component} from from "./${importPath}";`
...
customElements.get('${fileName}') as ${Component}
```
or
```ts
customElements.get<${Component}>('${fileName}')
```

2022-10-13 10:24 UTC, olkeoguz commented on README.md
> + <bl-alert variant="warning" icon>
Hope to include it soon then 😊 I changed it for now.

2022-10-13 11:35 UTC, muratcorlu approved these changes

2022-10-13 12:16 UTC, leventozen commented on scripts/generate-react-exports.js
> +  importStatements.push(`import ${Component} from "./${importPath}";`);
We are moving on this by adding type at `createComponent` function like this `createComponent<${Type}>`. After @olkeoguz added this, this conversation will be resolved.

2022-10-13 12:50 UTC, leventozen approved these changes

2022-10-13 12:55 UTC, merged