docs(dialog): improvement on docs
Trendyol/baklava pull request #609
Opened 2023-06-01 09:55 UTC by muratcorlu

This PR upgrades storybook version to the latest and improves storybook documentation of Dialog component in some ways:

* Story codes moved to separate TS file.
* Dummy text generated by an external library. ([lorem-ipsum](https://www.npmjs.com/package/lorem-ipsum))
* Code sample styling fixed.
* A "Contribute" section was added to the end.
* Inline styles converted to class definitions and inline style warning removed.
* Fixed some wording and added more explanation for some titles.

If this proposal gets approval, we can expand same style to the all of other components' documentation.

2023-06-01 10:57 UTC, AykutSarac requested changes

2023-06-01 10:57 UTC, AykutSarac commented on src/components/dialog/bl-dialog.mdx
> +Dialogs inform users about a task ansd can contain critical information, require decisions, or involve multiple tasks.
```suggestion
Dialogs inform users about a task and can contain critical information, require decisions, or involve multiple tasks.
```

There's a typo.

2023-06-01 11:54 UTC, AykutSarac approved these changes

2023-06-01 14:37 UTC, muratcorlu commented
@buseselvi I made small changes in dialog demos, so there are some visual changes. Please have a look at them and approve if everything is still fine.

2023-06-02 06:46 UTC, buseselvi approved these changes

2023-06-02 06:58 UTC, merged