feat(input): display type icons
Trendyol/baklava pull request #713
Opened 2023-09-26 09:04 UTC by AykutSarac

I decided that'd be a good idea to display icons depending on the type of the input.

> `icon` attribute overrides the default icon.

<img width="844" alt="image" src="https://github.com/Trendyol/baklava/assets/47941171/3025aee8-5357-45c1-946f-01ab7fa5b680">

```html
<bl-input type="search" />
<bl-input type="date" />
<bl-input type="date" icon="academy" />
<bl-input type="time" />
```

2023-09-27 07:17 UTC, muratcorlu commented
I think it will be nice to merge #712 first, then add default icons with this PR

2023-09-27 07:21 UTC, AykutSarac commented
> I think it will be nice to merge #712 first, then add default icons with this PR

Actually #712 has no crucial relevance with this PR so this could be reviewed separately.

2023-09-28 08:40 UTC, ogunb commented
Should we also update the clear button for type search with this PR? Or should there be another issue for it?

2023-09-28 08:44 UTC, muratcorlu commented
> Should we also update the clear button for type search with this PR? Or should there be another issue for it?

I think "clear button for input" is another story. Since some inputs (like search) already puts a native clear button in some browsers, but some others don't. Probably we'll need to make a generic decision that covers all types of inputs. It would be better to consider it separately.

2023-09-28 08:45 UTC, muratcorlu approved these changes
It looks good to me.

2023-09-28 08:47 UTC, muratcorlu requested changes
Unit and UI Test would be great.

2023-09-28 08:47 UTC, muratcorlu commented on src/components/input/bl-input.ts
> +    if (!this.icon) this.icon = inputTypeIcons[this.type];
I think it's better to have a test for this.

Also some examples in storybook would be helpful to check them visually.

2023-09-28 11:29 UTC, buseselvi approved these changes

2023-09-28 11:36 UTC, muratcorlu approved these changes
Good job! 🚀

2023-09-29 07:50 UTC, fatihhayri approved these changes

2023-09-29 08:02 UTC, merged