fix(checkbox): fix error state of checkbox/ checkbox group
Trendyol/baklava pull request #832
Opened 2024-04-21 21:58 UTC by ozkersemih

2024-04-25 20:02 UTC, doganozturk submitted a review, later dismissed

2024-04-25 20:08 UTC, AykutSarac requested changes

2024-04-26 07:23 UTC, ozkersemih commented on src/components/checkbox-group/bl-checkbox-group.ts
> +    });
i adde can you check again?

2024-04-26 12:05 UTC, doganozturk approved these changes

2024-04-26 13:32 UTC, merged