feat(select): search locale support #830
Trendyol/baklava pull request #843
Opened 2024-04-24 20:43 UTC by cenarturkmen

I added toLocaleLowerCase method for the search function of select. 
Also created a util method for getting locale. I'm not sure why we are not exporting getLocale from "configureLocalization"

2024-04-24 21:02 UTC, cenarturkmen commented
I couldn't link but issue: [830](https://github.com/Trendyol/baklava/issues/830)

2024-04-29 08:35 UTC, erbilnas requested changes

2024-04-29 08:35 UTC, erbilnas commented on src/localization.ts
>    const html = document.querySelector("html");
I believe we can do away with this line now

2024-04-29 08:35 UTC, erbilnas commented on src/localization.ts
>  type LangKey = "tr" | "en";
this one too

2024-04-29 08:40 UTC, ogunb requested changes

2024-04-29 08:40 UTC, ogunb commented on src/utilities/getLocale.ts
> +export const getLocale = (): LangKey => {
`configureLocalization` exposes a getLocale method. We can export that from localization.ts and use that instead. Issue detail might have been misleading sorry about that.

2024-04-29 08:41 UTC, ogunb commented
Also, would you be able to document this behavior in Storybook?

Thanks for your contribution btw

2024-05-22 18:48 UTC, ozkersemih approved these changes

2024-06-13 11:25 UTC, closed without merging

2024-06-13 11:42 UTC, buseselvi commented
Closed this as completed in [#857](https://github.com/Trendyol/baklava/pull/857). If there is something missing, we can open an issue separately. Thank you 🙏 @cenarturkmen