feat(icon): add door icon
Trendyol/baklava pull request #855
Opened 2024-05-06 09:43 UTC by umitkucuk

2024-05-06 10:04 UTC, buseselvi submitted a review, later dismissed

2024-05-07 06:19 UTC, umitkucuk commented
Hi @buseselvi, I also added the `credit_card` icon. fyi

2024-05-07 06:51 UTC, buseselvi submitted a review, later dismissed

2024-05-07 07:24 UTC, AykutSarac requested changes

2024-05-07 07:39 UTC, umitkucuk commented on src/components/icon/icons/door.svg
Done! Also informed the designer about the change.

2024-05-07 08:07 UTC, buseselvi approved these changes

2024-05-07 09:47 UTC, AykutSarac approved these changes

2024-05-07 09:50 UTC, merged