feat(datepicker): fix selected date color bug
Trendyol/baklava pull request #922
Opened 2024-10-07 13:36 UTC by dilandoogan

2024-10-07 14:26 UTC, erbilnas requested changes

2024-10-07 14:26 UTC, erbilnas commented on src/components/calendar/bl-calendar.css
> +    --bl-color-neutral-darker: var(--bl-color-neutral-full) !important;
Rather than relying on `!important,` I suggest using a more specific selector or introducing a new CSS variable

2024-10-08 11:05 UTC, erbilnas approved these changes

2024-10-08 12:07 UTC, AykutSarac approved these changes

2024-10-08 12:09 UTC, merged